% Generated by MetaNaviT after an approval-gated visualization plan.
% Source: bench/corpus/files/results/ablation.csv
script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(script_dir));
source_path = fullfile(repo_root, 'bench/corpus/files/results/ablation.csv');
output_path = fullfile(repo_root, 'doc/figures/mean-val-rmse-by-encoder.png');
warning('off', 'all');
fid = fopen(source_path, 'r');
assert(fid >= 0, 'Could not open spreadsheet');
data = textscan(fid, '%s%s%s%f%f', 'Delimiter', ',', 'HeaderLines', 1);
fclose(fid);
group = data{2};
metric = data{4};
groups = unique(group, 'stable');
values = zeros(numel(groups), 1);
counts = zeros(numel(groups), 1);
for i = 1:numel(groups)
    mask = strcmp(group, groups{i});
    counts(i) = sum(mask);
    values(i) = mean(metric(mask));
end

figure('Visible', 'off', 'Color', 'w');
scatter(1:numel(groups), values, 70, 'filled');
if ~strcmp('dot', 'histogram')
    set(gca, 'XTick', 1:numel(groups), 'XTickLabel', groups);
end
xlabel('encoder', 'Interpreter', 'none');
ylabel('mean val_rmse', 'Interpreter', 'none');
title('mean val_rmse by encoder', 'Interpreter', 'none');
grid on;
hold on;
plot([0.5, numel(groups)+0.5], [0.055, 0.055], '--r', 'LineWidth', 1.5);
legend('aggregate', 'baseline 0.055', 'Location', 'best');
hold off;
print(gcf, output_path, '-dpng', '-r140');
close(gcf);
